[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name        http
    Listen      0.0.0.0
    Port        8888
    Tag         agent.telemetry

[OUTPUT]
    Name        kafka
    Match       *
    Brokers     redpanda:9092
    Topics      agent.telemetry
    Format      json
